distros:
  archlinux: pacman
  debian: apt
  debian-12: apt
  debian-11: apt
  ubuntu: apt
  ubuntu-24: apt
  ubuntu-22: apt
  ubuntu-20: apt
  rocky: yum
  rocky-9: yum
  rocky-8: yum
download:
  archlinux: https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
  debian: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
  debian-12: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
  debian-11: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2
  ubuntu: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  ubuntu-24: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  ubuntu-22: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  ubuntu-20: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
  rocky: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-9: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-8: https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud.latest.x86_64.qcow2
images:
  archlinux: Arch-Linux-x86_64-cloudimg.qcow2
  debian: debian-12-generic-amd64.qcow2
  debian-12: debian-12-generic-amd64.qcow2
  debian-11: debian-11-generic-amd64.qcow2
  ubuntu: noble-server-cloudimg-amd64.img
  ubuntu-24: noble-server-cloudimg-amd64.img
  ubuntu-22: jammy-server-cloudimg-amd64.img
  ubuntu-20: focal-server-cloudimg-amd64.img
  rocky: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-9: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-8: Rocky-8-GenericCloud-Base.latest.x86_64.qcow2
files:
  apt:
    graphical:
      - install/20_graphical_apt.sh
    mirror:
      - install/20_localmirror_apt.sh
    proxmox:
      - per-boot/10_proxmox_step4.sh
      - per-boot/20_proxmox_step3.sh
      - per-boot/30_proxmox_step2.sh
      - per-boot/40_proxmox_step1.sh
  pacman:
    graphical:
      - install/20_graphical_pacman.sh
    mirror:
      - install/20_localmirror_pacman.sh
    minecraft:
      - install/20_minecraft_pacman.sh
    router:
      - install/pxe
      - install/pxe/pxelinux.cfg.default
      - install/20_router_pacman.sh
    pxe:
      - install/pxe
      - install/pxe/pxe.conf
      - install/pxe/pxe.preset
      - install/pxe/hooks
      - install/pxe/hooks/pxe
      - install/pxe/hooks/pxe_cifs
      - install/pxe/hooks/pxe_http
      - install/pxe/hooks/pxe_iscsi
      - install/pxe/hooks/pxe_nbd
      - install/pxe/hooks/pxe_nfs
      - install/pxe/hooks/pxe_nvmeof
      - install/pxe/hooks/pxe_wg
      - install/pxe/install
      - install/pxe/install/pxe
      - install/pxe/install/pxe_cifs
      - install/pxe/install/pxe_http
      - install/pxe/install/pxe_iscsi
      - install/pxe/install/pxe_nbd
      - install/pxe/install/pxe_nfs
      - install/pxe/install/pxe_nvmeof
      - install/pxe/install/pxe_wg
      - install/99_pxe_image.sh
  yum:
    graphical:
      - install/20_graphical_yum.sh
    mirror:
      - install/20_localmirror_yum.sh
setup:
  distro: archlinux
  options: []
  env_vars: []
  target: /dev/vda
  archiso_mirror: false
  pkg_mirror: |
    Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
    Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
  chaotic_mirror: |
    Server = https://geo-mirror.chaotic.cx/$repo/$arch

# == example usage ==
# setup:
#   distro: archlinux
# options:
#   - minecraft
# env_vars:
#   - MCSERVERMODE=create
# target: /dev/vda
# archiso_mirror: http://local.mirror.internal:8080/$repo/os/$arch
# pkg_mirror: |
#   Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
#   Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
# chaotic_mirror: |
#   Server = https://geo-mirror.chaotic.cx/$repo/$arch